### PR TITLE
Fix bombs

### LINKED ISSUE #155: Fix players can get stuck between wall and bomb

### PR DESCRIPTION
**Pull request by Lea1496**
- fix player not being hit when on bomb tile
- fix player can get stuck in wall when dropping bomb

closes #155

### CODE REVIEW

File: Booom/Assets/Scripts/Bombs/Bomb.cs [hunk 1]
```diff
@@ -115,6 +119,7 @@ protected virtual void PaintTiles()
         PlayerEnum newTileOwner = GameManager.Instance.IsSpreadingMode ? currentOwner : AssociatedPlayer;
 
         ChoosePaintTile(bombTile, newTileOwner);
+        HitPlayers(_bombCoordinates, Vector2Int.zero);
```
Comment (DrPickle3) [inline Booom/Assets/Scripts/Bombs/Bomb.cs]: On lavait actually juste enlever par accident? Lol
